### ISSUE TITLE
Bug during inference

### ISSUE THREAD

**Issue by n-mourdou** [Linzy19/TaxDiff#3]
Hello, 

I am trying to generate some sequences, following your instructions, but it seems that there is a bug. 

I get the following RuntimeError:

```
# class_lables tensor([1204, 1204, 1204, 1204, 1204, 1204, 1204, 1204, 1204, 1204],
       device='cuda:0')
  0% 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/TaxDiff/sample_protein.py", line 114, in <module>
    main(args,class_lables)
  File "/content/TaxDiff/sample_protein.py", line 60, in main
    samples = diffusion.p_sample_loop(
  File "/content/TaxDiff/diffusion/gaussian_diffusion.py", line 450, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/content/TaxDiff/diffusion/gaussian_diffusion.py", line 501, in p_sample_loop_progressive
    out = self.p_sample(
  File "/content/TaxDiff/diffusion/gaussian_diffusion.py", line 402, in p_sample
    out = self.p_mean_variance(
  File "/content/TaxDiff/diffusion/respace.py", line 92, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/content/TaxDiff/diffusion/gaussian_diffusion.py", line 279, in p_mean_variance
    model_output = model(x, t, **model_kwargs)
  File "/content/TaxDiff/diffusion/respace.py", line 129, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/content/TaxDiff/models.py", line 278, in forward_with_cfg
    model_out = self.forward(combined, t, y)
  File "/content/TaxDiff/models.py", line 264, in forward
    c = t + y                                # (N, D)
RuntimeError: The size of tensor a (1000) must match the size of tensor b (20) at non-singleton dimension 0
```

Any help would be appreciated!

**Comment by Linzy19** [comment]
Thanks, we have fix this bug in the newest update version.

**Comment by n-mourdou** [comment]
Could you explain what you mean by the latest version? I downloaded the weights from HuggingFace and cloned the repo **today** and I encountered the bug.

**Comment by Linzy19** [comment]
To verify that the generated code works, I re-run the code locally. And to ensure the integrity of ckpt, we put out both a new version of ckpt and dataset to HuggingFace. You can try again.
![image](https://github.com/user-attachments/assets/58308139-32a3-417d-aeb3-134922874c56)
